//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DivingGear.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class DivingGear extends Item {
	public boolean IsTheSame(DivingGear d) {
	}
	
	public boolean Equip(Player p) {
	}
}
