//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Food.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class Food extends Item {
	public boolean Use(Player p) {
	}
	
	public boolean IsTheSame(Food f) {
	}
}
