//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class Game {
	private String state;
	private int playersInWater;
	private IceField fields;
	private Player players;
	private Player activePlayer;
	private void Storm() {
	}
	
	public boolean IsEveryoneHere(IceField f) {
	}
	
	private void CreateFields() {
	}
	
	public void Over(boolean victory) {
	}
	
	private void RoundOver() {
	}
	
	public void NextPlayer() {
	}
	
	public void PlayerSaved() {
	}
	
	public void PlayerFellInWater() {
	}
}
