//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IceField.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class IceField {
	private int snowLevel;
	private int capacity;
	private Object hasIgloo;
	private Item item;
	private Player players;
	private IceField neighbours;
	private Player players;
	private void Capsize() {
	}
	
	public IceField GetNeighbour(Direction d) {
	}
	
	public void RemoveSnow(int a) {
	}
	
	public void Storm() {
	}
	
	public void BuildIgloo() {
	}
	
	public boolean CountGunParts(FlareGunPart f) {
	}
	
	public void Accept(Player p) {
	}
	
	public boolean Save(IceField f) {
	}
	
	public void Remove(Player p) {
	}
	
	public boolean TakeItem(Player p) {
	}
	
	public void AddNeighbour(Direction d, IceField f) {
	}
	
	public void RevealCapacity() {
	}
}
