//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rope.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class Rope extends Item {
	public boolean Use(Player p) {
	}
	
	public boolean IsTheSame(Rope r) {
	}
}
