//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shovel.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class Shovel extends Item {
	public boolean Use(Player p) {
	}
	
	public boolean IsTheSame(Shovel s) {
	}
}
