package szkeleton;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eskimo.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class Eskimo extends Player {
	public void UseAbility(Direction d) {
	}
	
	public void UseAbility(Direction d) {
	}
}
