package szkeleton;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eskimo.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//



public class Eskimo extends Player {
	
	/**
	 * Az eszkimó használja a képességét, mellyel épít egy iglut.
	 */
	public void UseAbility(Direction d) {
		MethodPrinter.Println(Skeleton.GetName(this) + ".UseAbility(Direction d");
		MethodPrinter.IncreaseIndentation();
		field.BuildIgloo();
		MethodPrinter.DecreaseIndentation();
	}
}
