package szkeleton;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Food.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class Food extends Item {
	public boolean Use(Player p) {
		MethodPrinter.Println(Skeleton.GetName(this) + ".Use(" + Skeleton.GetName(p) + ")");
		MethodPrinter.IncreaseIndentation();
		boolean result = MethodPrinter.AskQuestion("Tud enni a karakter?");
		if(result)
			p.ChangeTemperature(1);
		MethodPrinter.DecreaseIndentation();
		return result;
	}
	
	public boolean IsTheSame(Food f) {
		MethodPrinter.Println(Skeleton.GetName(this) + ".IsTheSame(" + Skeleton.GetName(f) + ")");
		return true;
	}
}
