package szkeleton;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//


public class Game {
	//private String state;
	//private int playersInWater;
	private ArrayList<IceField> fields;
	private ArrayList<Player> players;
	private Player activePlayer;
	
	Game(){
		MethodPrinter.Println("Game constructor");
	}
	
	private void Storm() {
		MethodPrinter.Println("Game.Storm()");
		for(IceField f : fields){
			f.Storm();
		}
	}
	
	public boolean IsEveryoneHere(IceField f) {
		MethodPrinter.Println("Game.IsEveryoneHere(Field f)");
		return MethodPrinter.AskQuestion("Mindenki ezen a mezõn áll?");
	}
	
	private void CreateFields() {
		MethodPrinter.Println("Game.CreateFields()");
	}
	
	public void Over(boolean victory) {
		MethodPrinter.Println("Game.Over(boolean victory)");
	}
	
	private void RoundOver() {
		MethodPrinter.Println("Game.RoundOver()");
		if(MethodPrinter.AskQuestion("Van valaki vízbe esve?"))
			Over(false);
		for (IceField f : fields) 
			f.Storm();
	}
	
	public void NextPlayer() {
		MethodPrinter.Println("Game.NextPlayer()");
		int idx = players.indexOf(activePlayer);
		if(idx == players.size()-1) {
			RoundOver();
			idx = 0;
		}
		else
			idx++;
		players.get(idx).SetRemainingActions(4);
	}
	
	public void PlayerSaved() {
		MethodPrinter.Println("Game.PlayerSaved()");
	}
	
	public void PlayerFellInWater() {
		MethodPrinter.Println("Game.PlayerFellInWater()");
	}
	
	public void SetFields(ArrayList<IceField> f) {
		fields = f;
	}
	public void SetPlayers(ArrayList<Player> p) {
		players = p;
	}
	public void SetActivePlayer(Player p) {
		activePlayer = p;
	}
}
