package szkeleton;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public abstract class Item {
	public boolean Use(Player p) {
	}
	
	public boolean Equip(Player p) {
	}
	
	public boolean IsTheSame(Item i) {
	}
}
