package szkeleton;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Researcher.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class Researcher extends Player {
	
	/**
	 * A kutató használja a képességét, mellyel felderít egy szomszédos mezőt.
	 */
	public void UseAbility(Direction d) {
		MethodPrinter.Println(Skeleton.GetName(this) + ".UseAbility(Direction d)");
		MethodPrinter.IncreaseIndentation();
		IceField researchedfield = field.GetNeighbour(d);
		researchedfield.RevealCapacity();
		MethodPrinter.DecreaseIndentation();
	}
}
