package szkeleton;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rope.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class Rope extends Item {
	public boolean Use(Player p1) {
		MethodPrinter.Println(Skeleton.GetName(this) + ".Use(" + Skeleton.GetName(p1) + ")");
		MethodPrinter.IncreaseIndentation();
		IceField f1 =  p1.GetField();
		boolean success = false;
		for (Direction d : Direction.values()) {
			IceField f = f1.GetNeighbour(d);
			if(f.Save(f1))
				success = true;
		}
		MethodPrinter.DecreaseIndentation();
		return success;
	}
	
	public boolean IsTheSame(Rope r) {
		MethodPrinter.Println(Skeleton.GetName(this) + ".IsTheSame(" + Skeleton.GetName(r) + ")");
		return true;
	}
}
