package szkeleton;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shovel.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class Shovel extends Item {
	public boolean Use(Player p) {
		MethodPrinter.Println(Skeleton.GetName(this) + ".Use(" + Skeleton.GetName(p) + ")");
		MethodPrinter.IncreaseIndentation();
		IceField f =  p.GetField();
		boolean result = MethodPrinter.AskQuestion("Van hó a mezõn?");
		if(result)
			f.RemoveSnow(2);
		MethodPrinter.DecreaseIndentation();
		return result;
	}
	
	public boolean IsTheSame(Shovel s) {
		MethodPrinter.Println(Skeleton.GetName(this) + ".IsTheSame(" + Skeleton.GetName(s) + ")");
		return true;
	}
}
